### ISSUE TITLE
adjust endpoints to REST standards

### ISSUE THREAD

**Issue by francav** [wkspower/wks-platform#116]
- GET /variable/{processInstanceId} should be /variable?processInstanceId=:processInstanceId
	- GET /process-definition/{bpmEngineId}/{processDefinitionId}/xml - this is probably old stuff. We don't want bpmEngineId in the API but auto-discoverable
	- PATCH /case-definition/{caseDefId} - Maybe this is UPDATE instead since is replacing the entire resource record
	- PATCH /case/{businessKey} - can we define the mergePatch schema? Current stage will only show "string" as the request body in Swagger
	- PATCH /case/{businessKey}/comment/{commentId} - should it be UPDATE instead?
	- PATCH /queue/{queueId} - should id be UPDATE instead?
	- name for record-controller (see swagger endpoint title)
	- PATCH /record-controller/{id} - should it be UPDATE
	- name for record-type-controller (see swagger endpoint title)
	- PATCH /record-type-controller/{id} - should it be UPDATE
	- name for data-import-controller (see swagger endpoint title)
	- name for data-export-controller (see swagger endpoint title)
	- name for deployment-controller (see swagger endpoint title)

	- processDefinitionId -> id on process-definition endpoints
	- taskId -> id on task endpoints
	- formKey -> key on form endpoints
	- caseDefId -> id on case-definition endpoints
	- queueId -> id on queue endpoints
	- recordTypeId -> id on queue endpoints

**Comment by sindhunaydu** [comment]
@francav I would like to work on this, can you assign it to me?

**Comment by francav** [comment]
Thanks @sindhunaydu

**Comment by francav** [comment]
And feel free to reach out since the task description may be too high level @sindhunaydu

**Comment by sindhunaydu** [comment]
Hi @francav, I've started working on this and have a few questions, 
1. `GET /process-definition/{bpmEngineId}/{processDefinitionId}/xml.. auto-discoverable` - can you explain this please?
2. `PATCH /case/{businessKey} - can we define the mergePatch schema?`  - can you explain this as well?
3. `name for *-controller (see swagger endpoint title)` - we can use `@Tag` annotation to provide a name for the controller, is that the requirement? If so, what would be the preferred names for the controllers?

Thanks!

**Comment by francav** [comment]
Hi @sindhunaydu 

1 - it needs to be deleted
2 - it may need a bit of investigation on how to formalize the body of this endpoint since the parameter is a string(see how swagger shows the body structure). We can leave this for another issue if we don’t know how to deal with it for now.
3 - Import, Export and Deployment

Thanks!

**Comment by sindhunaydu** [comment]
Hi @francav I created a PR with the changes, but looks like there are new changes in the same files after I forked the repo causing conflicts. I dont have write access so I'm unable to see the conflicts. Will those changes overwrite my changes?

**Comment by sindhunaydu** [comment]
@francav PR created - #144

**Comment by francav** [comment]
Hi @sindhunaydu, thanks for the great work. Sorry for bringing this now, but I have just realised we neet to check on the impacts of these changes at the react app.
Would you be able to do that check on the files at apps/react/case-portal/src/services ?

**Comment by sindhunaydu** [comment]
@francav I made changes to the JS files. Quick question, how do I run the local changes on my machine? Is there a way for me use my local changes with the docker setup?

**Comment by francav** [comment]
Thanks @sindhunaydu. You can follow this guide to configure your local dev enviroment: https://docs.wkspower.com/docs/instalation-guide
