### ISSUE TITLE
Open Policy docker image does not contain the "queue" policy

### ISSUE THREAD

**Issue by ricczud** [wkspower/wks-platform#137]
Symptom:
The queue endpoint on the portal fails to retrieve the data returning a 403 status code.

Root cause:
The path policy for "queue" is missing in the "wks_policy_rules.rego" file in the image.

Resolution:
Rebuild the opa image locally from the main repository, which includes the correct policy.

**Comment by francav** [comment]
Verified that queue rule is in the rego file. However, that was not tagged yet then the last deployed docker image won’t have it. This is probably why you got the error - using the deployed opa image along with other locally built components(UI, api, etc).
Maybe we need to improve this docker image deployment process.

**Comment by francav** [comment]
The tag version for the opa image hadn't been updated. 
Fixed at https://github.com/wkspower/wks-platform-docker/commit/7a0d0362da8e6a9a0faf6c400626fd1205d17272
