### ISSUE TITLE
(documentation): Installation Option 2: Running with Docker Compose Images

### ISSUE THREAD

**Issue by francav** [wkspower/wks-platform#243]
## **Issue description**
As a devop, I encountered challenges while trying to host the WKS Power platform on a remote server. The current documentation mainly focuses on localhost setups, and I struggled to find clear guidance for remote hosting. To improve user experience, a guide or additional resources dedicated to remote hosting would be beneficial.

## **Proposed Solution**
A comprehensive guide for deploying the WKS Power platform on remote servers would be helpful. This guide could include:
 - Explain how multi-tenancy is designed and roles/requirements of Keycloak realms names and database names
 - Server requirements and setup configurations.
 - Common issues related to remote hosting and recommended solutions.
 - Tips for customizing environment variables and .yml/.yaml files.
 - Best practices for Keycloak and related security setups.

I'm hoping the guide to outlines best practices for hosting the WKS Power platform on a remote server. Since I've encountered some issues running it on a remote server, I'm hoping that we can work together to find a solution.

**Comment by francav** [comment]
@Thanaphat-Kalaya Some initial context:

The existing multi-tenancy framework is structured around remote deployment URLs following this format: tenant_id.somedomain (e.g., saasCustomer1.wksplatform.com). This setup entails the creation of one Keycloak realm and one MongoDB database specifically designated for each tenant, such as saasCustomer1.

**Comment by francav** [comment]
We can certainly explore alternatives for this design. If that's the case, please open another feature request with requirements.

**Comment by Thanaphat-Kalaya** [comment]
I believe our existing multi-tenancy framework is robust and well-suited for our current needs. Developing alternatives might be quite time-consuming and perhaps unnecessary at this stage.

Instead, I suggest we focus on simplifying the installation process. By enhancing our current guides and potentially introducing automation tools, we can significantly improve user experience and accessibility without a major overhaul.

Here's what I suggest:
- **Enhanced Documentation:** Clear, step-by-step guides could help alleviate confusion.
- **Automation Scripts:** These could streamline the setup process and minimize errors.

These improvements could make a significant difference. Looking forward to hearing your thoughts!

**Comment by Thanaphat-Kalaya** [comment]
As for the introduction of the guide, I drafted one with some docs outline from your given initial context. Correct me if I'm wrong or misunderstand something. If you confirm the introduction is correct and this guide outline is fine, then I'll put them to develop branch soon.

##################################################################################

# Comprehensive Guide for Deploying the WKS Power Platform on Remote Servers
## Introduction
Multi-tenancy on the WKS Power Platform is designed to provide each tenant with a secure and isolated operational environment, akin to providing separate office suites within a single corporate building. This architecture allows service providers to manage multiple clients efficiently while ensuring that each client's data and operations remain private and secure.
## Architectural Overview
### Tenant URL Structure:
- Each tenant accesses their environment through a unique subdomain, following the format tenant_id.somedomain.com (e.g., saasCustomer1.wksplatform.com).
- This subdomain serves as the dedicated entry point to the tenant’s specific portion of the platform, ensuring direct and secure access.
### Keycloak Realms:
- Each tenant has a separate Keycloak realm, providing a dedicated security domain that controls authentication and authorization. This setup ensures that user credentials and permissions are managed locally within each tenant's realm, enhancing security and privacy.
- Upon onboarding a new tenant, a realm is specifically created and configured with unique security settings and user management protocols tailored to meet the tenant's needs.
### MongoDB Databases:
- Each tenant has a separate database to store tenant-specific data securely and maintain complete data isolation between tenants.
- Creating a dedicated MongoDB database for each new tenant setup, ensuring that data from one tenant is completely inaccessible to another.

##################################################################################

# Installation Guide
## Prerequisites
> List the minimum and recommended server specifications for running the platform remotely.
## Initial Setup
> Step-by-step guide on configuring servers to meet the platform’s operational requirements. May include network configurations as needed.
## Customizing Environment Variables and Configuration Files
### Environment Variables
> Instructions on how to effectively set and customize environment variables.
### Configuration File Management
> Tips on managing .yml/.yaml files, including common tweaks and optimizations.
## Installing the WKS Power Platform
> Detailed steps for installing the platform, including downloading necessary software, deploying services, and initial service configuration.
## Post-Installation Checks
> Checklist to ensure everything is set up correctly and running as expected.

##################################################################################

# Troubleshooting Common Issues
## Identifying Common Problems
> A list of frequent issues encountered during remote deployments.
## Recommended Solutions
> Practical solutions and troubleshooting steps for each listed problem.

##################################################################################

# Security Best Practices
## Keycloak Security Setups
> Detailed best practices for configuring Keycloak in a remote environment to ensure robust security.
## General Security Tips
> General advice on maintaining the security integrity of the platform when hosted remotely.

##################################################################################

**Comment by francav** [comment]
Sounds an excelent starting point @Thanaphat-Kalaya 
Just wondering if there is a easier way for us to collaborate on this doc. Would you suggest something? https://www.notion.so ?

**Comment by Thanaphat-Kalaya** [comment]
Thanks for the suggestion! I haven't used Notion before for document collaboration, but I'm eager to give it a try—it sounds like a great tool.

Anyway, it seems like Notion isn't a free tool for non-individual use. Alternatively, I'm familiar with Google Docs but not for this job, which could be another easy option for real-time collaboration. Let me know what you think would work best for our needs.

By the way, I'm trying to push my docs changes to develop branch but I didn't have permission to do so. Did I need to fork the repo?

**Comment by francav** [comment]
> Thanks for the suggestion! I haven't used Notion before for document collaboration, but I'm eager to give it a try—it sounds like a great tool.
> 
> Anyway, it seems like Notion isn't a free tool for non-individual use. Alternatively, I'm familiar with Google Docs but not for this job, which could be another easy option for real-time collaboration. Let me know what you think would work best for our needs.

I am happy with the one if quicker for us to start collaborate. No problem with google docs

> By the way, I'm trying to push my docs changes to develop branch but I didn't have permission to do so. Did I need to fork the repo?

We can't push straight to develop. You need to branch from develop, push it and then create a pull request. Let me know if you need help with it.

**Comment by Thanaphat-Kalaya** [comment]
> I am happy with the quicker for us to start collaborate. No problem with google docs

Do you want me to create the docs or do you prefer to do it yourself?

> We can't push straight to develop. You need to branch from develop, push it and then create a pull request. Let me know if you need help with it.

I tried to create a branch, but I still can't push into it. Did I mess up somewhere?

**Comment by francav** [comment]
> > I am happy with the quicker for us to start collaborate. No problem with google docs
> 
> Do you want me to create the docs or do you prefer to do it yourself?
> 
would you mind creating it and sharing it with me?

> > We can't push straight to develop. You need to branch from develop, push it and then create a pull request. Let me know if you need help with it.
> 
> I tried to create a branch, but I still can't push into it. Did I mess up somewhere?

hey, what do you think about joining a discord server I just created and we take it from there? https://discord.gg/xWgzcPV5
