### ISSUE TITLE
Bug: CORS Error on File Uploads After forms.io Dependency Upgrade

### ISSUE THREAD

**Issue by Thanaphat-Kalaya** [wkspower/wks-platform#249]
**Environment:**

*   **Browser(s) Tested:** Chrome, Edge, Safari
*   **Operating System:** Windows, macOS

**Description:** A CORS error occurs during file uploads following a recent upgrade to the forms.io dependency. The error manifests as malformed URLs containing 'undefined' segments during the upload process, likely triggered by changes introduced in the dependency upgrade.

**Steps to Reproduce:**

1.  Navigate to the file upload section of any case.
2.  Select any file to upload.
3.  The upload fails with a CORS error.

**Expected Result:** Files should upload successfully without triggering CORS errors.

**Actual Result:** File uploads fail due to CORS errors, with URLs improperly formed, showing parts as 'undefined'. This behavior is consistent with the post-upgrade of the forms.io dependency.

**Additional Information:**

*   The issue has been consistently reproducible across different client setups and browsers.
*   The problem correlates with the timing of the forms.io upgrade, suggesting a causative link.

**Logs and Error Messages:**

*   Network logs indicate malformed URLs during the upload process.
*   CORS error messages specify disallowed origins due to the malformed URLs.

**Screenshots/Attachments:**

![image](https://github.com/wkspower/wks-platform/assets/168273927/7ee053bc-2970-4f65-a0ad-6a58c06ffb81)

**Analysis:** It appears that the upgrade to forms.io has altered how file data is processed or how URLs are constructed within the application. Given that this issue aligns with the timing of the upgrade, the focus should be on reviewing the changes made in the latest forms.io version that could impact URL formation or CORS policies.

**Suggested Next Steps:**

*   Examine the changes in the latest forms.io release notes for any modifications related to file handling or URL generation.
*   Test downgrading forms.io to a previous version to confirm if the issue is resolved, thus isolating the problem from the upgrade.
*   Contact forms.io support or review community forums for any similar issues reported by other users.

**Impact:** This bug prevents users from uploading files, critically impacting functionalities that depend on file inputs.

**Comment by francav** [comment]
The issue is probably related to file handling within forms.io. To investigate:

https://github.com/wkspower/wks-platform/blob/7bb85596202a482515f7969729890650c9af8e68/apps/react/case-portal/src/views/caseForm/newCaseForm.js#L131-L137

https://github.com/wkspower/wks-platform/blob/7bb85596202a482515f7969729890650c9af8e68/apps/react/case-portal/src/plugins/storage/index.js#L6-L20
