### ISSUE TITLE
Installation on Azure Container/K8s services using High Availability for each involved component

### ISSUE THREAD

**Issue by shantanuv** [wkspower/wks-platform#299]
Are there any instructions available to set the WKS platform on azure using Container/K8s services? 

Using the docker scripts available, it is easy to do so on Azure as a standalone/development setup. But what would be interesting to do is to create a HA setup - with each of the involved services (MongoDB, MinIO, OPA etc.)  also being available in a minimum possible high availability setup.

Thanks

**Comment by francav** [comment]
Hi @shantanuv,

We offer cloud setups including HA as part of WKS Power consutancy services with a great expertise using gitops, ArgoCD and k8s. Please, reach out to our team at https://wkspower.com/contact-us-wks-platform.

Regards,

Victor Franca

**Comment by shantanuv** [comment]
That helps !! Thanks @francav.
